name: Build and Deploy
on: 
  workflow_dispatch: 
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: |
          docker build -t myapp:latest .
      - name: Sign in to Azure
        uses: azure/login@v2
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Push to ACR
        run: |
          az acr login -n labdeployacrels
          docker tag myapp:latest labdeployacrels.azurecr.io/myapp:latest
          docker push labdeployacrels.azurecr.io/myapp:latest
      - name: Deploy to WebApp
        run: |
          az webapp config container set \
          -g RGLabDeploy-Els \
          -n labdeploy-webapp-els \
          --container-image-name labdeployacrels.azurecr.io/myapp:latest \
          --container-registry-url https://labdeployacrels.azurecr.io \
          --container-registry-user ${{secrets.ACR_USER}} \
          --container-registry-password ${{secrets.ACR_PWD}}
